### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by altayhunter** [ashbash1987/ktanemod-pianokeys#1]
> download the latest release of the module, and drop the ColourFlash folder into the '<path>/<to>/Keep Talking and Nobody Explodes/mods' folder.

The instructions say to copy the `ColourFlash` folder from the repository, but there doesn't seem to be any such folder.

**Comment by ashbash1987** [comment]
Apologies, that's just a copy and paste issue from my other module's README. I'll my just fix that now.

**Comment by altayhunter** [comment]
I don't see a `PianoKeys` folder in the repo either. Is it just the whole `Assets` folder I need to copy over?

**Comment by ashbash1987** [comment]
There's a build in the releases page https://github.com/ashbash1987/ktanemod-pianokeys/releases that contains what you need to get going.

**Comment by altayhunter** [comment]
Ah, I see now. Thanks!
